ALTER TABLE orders ADD CONSTRAINT profile_orders_fk
FOREIGN KEY (PROFILE, PROCEDR)
REFERENCES profile (ID, PROCEDR)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE orders ADD CONSTRAINT procedur_orders_fk
FOREIGN KEY (PROCEDR)
REFERENCES procedur (ALPHA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE encountr ADD CONSTRAINT patient_encountr_fk
FOREIGN KEY (PATIENT)
REFERENCES patient (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE encountr ADD CONSTRAINT insuranc_encountr_fk
FOREIGN KEY (INSURANCE)
REFERENCES insuranc (CODE)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE encountr ADD CONSTRAINT facility_encountr_fk
FOREIGN KEY (OrderingFacility)
REFERENCES facility (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE encountr ADD CONSTRAINT doctors_encountr_fk
FOREIGN KEY (DOCTOR)
REFERENCES doctors (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE encordr ADD CONSTRAINT encountr_encordr_fk
FOREIGN KEY (ENCOUNTER)
REFERENCES encountr (NUMBER)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE orders ADD CONSTRAINT encountr_orders_fk
FOREIGN KEY (ENCOUNTER)
REFERENCES encountr (NUMBER)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
