SELECT
  ID
, NOTES
, Street
, FacilityID1
, TYPE
, GatewayNumber
, LabType
, NAME
, DoctorID
, MsgFldType
, PrintName
, ADDRESS
, Street1
, Street2
, STATAlways
, STATDestination
, CITY
, STATE
, County
, Country
, ZIP
, PhoneNum
, CONTACT
, DEST
, SRC
, CONTYPE
, CONPHONE
, RateCode
, SCHED
, HCType
, hcStatus
, HCDestination
, HCSourceDir
, HCDestination1
, HCTransport
, HCMode
, HCProtocol
, HCInterval
-- , PASSWORD
, Route
, Route_Stop
, DefaultPrinterID
, PrintPatientChart
, Rmt_Copies
, TreshholdDate
, Report_ID
, Copies
, Reqform
, ChartReportID
, PatChartCopies
, PatientChartPrinter
, SendEMail
, EMailAddress
, Days
, StandingOrderStatus
, StandingOrderFrequen
, DayofWeek
, DayofMonth
, WeekofMonth
, LastProcessedDate
, AllowMerge
, AlertPrint
, AlertPrinter
, AlertStation
, AlertStationName
, AlertEMail
, AlertEMailAddress
, AlertPager
, AlerPagerNbr
, AlertFax
, AlertFaxNbr
, AlertCall
, AlertCallNbr
, SendResultEDIMSG
, SendResultsEDIMSGID
, SendResultsPrint
, SendResultsPrinter
, SendResultsEMail
, SendResultsEMailAddr
, SendResultsPager
, SendResultsPagerNbr
, SendResultsFax
, SendResultsFaxNbr
, SendResultsCall
, SendREsultsCallNbr
, StatNotifyPager
, StatNotifyPrint
, StatNotifyPrinter
, StatNotifyPagerNbr
, StatNotifyEMail
, StatNotifyEMailAddre
, StatNotifyFax
, StatNotifyFaxNbr
, StatNotifyCall
, StatNotifyCallNbr
, InPatient
, PowerAlertStationNam
, Status
, Transport
, Protocol
, DoNotValidateFacIDIn
, SegmentSeperator
, FieldSeperator
, ComponentSeperator
, SubComponentSeperato
, RepetitionSeperator
, EscapeCharacter
, CharacterSet
, EncodingRules
, DataEncryption
, HostName
, Port
, ServiceName
, TransportEncryption
, DataFormat
, AckDelay
, ResendCount
, SupportsPowerMESSAGE
, MSGSet
, AFTLikeFacility
, ScriptCodeForProcess
, A_Summary
, P_Summary
, InLineDescr
, Pend_Tests
, FIRST_REPORT
, PART_REPORT
, PAN_DOCID
, UseDefaultDoctor
, DefaultDocID
, UpdatePATForOrders
, IDToPutInHISPatientI
, GrpRateCode
, Longitude
, Latitude
, ServiceBy
, ConnectionLikeFacili
, SalesRepresentative
, SignUpDate
, Phlebotomist
, PMPrintSpecimenLabel
, PMPrintRequisitionLa
, PMPrintMicroLabel
, PMPrintRequisitionRe
, ByPassClaimCreation
, CapitationType
, CapitationMembers
, SlidingFeeSupported
, CLIANumber
, SupportHandlingFee
, PrintEpiReports
, GroupID
, SeqInGroup
, DefaultDoctor
, LOGO
, WaitForPatient
, ValidOrdersProfile
, InvoiceFormat
, InvoiceVersionID
, TestGroupID
, PrivateClinic
, SendReportToBothWard
, CannedText
, Terms
, LateFee
, PrintOnInvoice
, BillTo
, LogoFileName
, Patientclass
, VisitType
, UpdateDate
, UpdateTime
, UserID
, OwnerID
FROM FACILITY