use jwplayerbi_current;
create table vin_code_lookup (
	lookup_pk integer not null auto_increment,
    sku varchar(65),
    rpt_code varchar(65),
    primary key (lookup_pk)
);

drop index idx_vcl_sku on vin_code_lookup;
alter table vin_code_lookup add index idx_vcl_sku (sku);

truncate vin_code_lookup;
insert into vin_code_lookup ( sku, rpt_code) values  
(null, 'none'),
( 'JWE_ADS_ANNUAL', 'ads'),
( 'JWE_ADS_MONTHLY', 'ads'),
( 'JWE_ADS_OVERAGE_1000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_10000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_100000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_1500', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_15000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_2000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_20000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_200000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_21000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_250', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_2500', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_25000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_3000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_30000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_300000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_3500', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_35000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_4000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_4500', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_500', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_5000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_50000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_500000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_6000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_7000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_70000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_750', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_750000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_8000', 'Ads_Overage'),
( 'JWE_ADS_OVERAGE_80000', 'Ads_Overage'),
( 'JWE_HOSTING', 'hosting'),
( 'JWE_HOSTING_OVERAGE_10', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_100', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_1000', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_10000', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_150', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_1500', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_200', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_2000', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_25', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_250', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_300', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_3000', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_400', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_450', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_4500', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_50', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_500', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_600', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_700', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_75', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_800', 'hosting_overage'),
( 'JWE_HOSTING_OVERAGE_900', 'hosting_overage'),
( 'JWE_STREAMING', 'streaming'),
( 'JWE_STREAMING_OVERAGE_100', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_1000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_10000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_100000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_1250', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_12500', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_125000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_150', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_1500', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_15000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_150000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_1750', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_17500', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_2000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_20000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_2100', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_250', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_2500', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_250000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_300', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_3000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_30000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_3500', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_400', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_4000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_4500', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_50', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_500', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_5000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_600', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_6000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_7000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_750', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_75000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_800', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_8000', 'stream_overage'),
( 'JWE_STREAMING_OVERAGE_9000', 'stream_overage'),
( 'JWP_ENTERPRISE_ANNUAL', 'Enterprise'),
( 'JWP_ENTERPRISE_ANNUAL2', 'Enterprise'),
( 'JWP_ENTERPRISE_MONTHLY', 'Enterprise'),
( 'JWP_ENTERPRISE_MONTHLY2', 'Enterprise'),
( 'JWP_PREMIUM', 'Premium'),
( 'JWP_PREMIUM_MONTHLY', 'Premium'),
( 'JWP_PRO', 'Pro'),
( 'SDK_Android_100K_Monthly', 'Android'),
( 'SDK_Android_10K_Annual', 'Android'),
( 'SDK_Android_1K_Monthly', 'Android'),
( 'SDK_Android_20K_Monthly', 'Android'),
( 'SDK_Android_50K_Monthly', 'Android'),
( 'SDK_Android_Annual', 'Android'),
( 'SDK_Android_Monthly', 'Android'),
( 'SDK_iOS_10K_Monthly', 'ios'),
( 'SDK_iOS_1K_Monthly', 'ios'),
( 'SDK_iOS_20K_Monthly', 'ios'),
( 'SDK_iOS_Annual', 'ios'),
( 'SDK_iOS_Monthly', 'ios'),
( 'Total Tax', 'tax'),
( 'VIN_AutoBillCreditConversion', 'misc'),
( 'VIN_Credit', 'misc'),
( 'VIN_OverageAutoBill', 'misc'),
( 'VIN_PartialTxBPayment', 'misc'),
( 'VIN_PM_VALIDATION', 'misc')
;